# Generated by Django 4.2.6 on 2023-10-22 11:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_worker_inviter_alter_worker_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('user', 'board')},
        ),
    ]
