# Generated by Django 4.2.6 on 2023-10-22 11:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_alter_worker_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Worker',
            new_name='WorkerMessage',
        ),
    ]
