# Generated by Django 4.2.6 on 2023-10-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_worker_workermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermessage',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
