# Generated by Django 4.2.6 on 2023-10-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_activworker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activworker',
            unique_together={('board',)},
        ),
        migrations.RemoveField(
            model_name='activworker',
            name='user',
        ),
    ]
