# Generated by Django 4.2.6 on 2023-10-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='worker_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
