# Generated by Django 4.2.6 on 2023-10-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_worker_code_workercode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workercode',
            unique_together={('user',)},
        ),
    ]
